version: '3.6'
services:
    jupyter:
        build: .
        container_name: jupyter
        ports:
          - 8888:8888
        volumes:
            - ./:/work
        working_dir: /work

volumes:
    jupyter:
        driver: local
